
import random
import io

import PIL.Image

import question
from fsagen import *


def language_of_fsa(n_choices=4):
    """
    Generate question about language of a given FSA.
    """
    fsa_set = random.choice(FSA_SETS)
    fsas = random.sample(fsa_set, n_choices)
    # fsas = [func() for func in myfuncs]

    answeridx = random.randrange(n_choices)
    target_fsa = fsas[answeridx][0]

    prompt = "What language is generated by the FSA shown below?"
    buffer = target_fsa.to_pydot().create_png()
    img = PIL.Image.open(io.BytesIO(buffer))
    choices = [desc for fsa, desc in fsas]
    return question.MultipleChoiceQuestion(prompt, choices, answeridx,
                                           promptfigure=img)


FSAS_2SYM = [
    even_a(2, 0),
    even_a(2, 1),
    odd_a(2, 0),
    odd_a(2, 1),
    exactly_2_a(2,0),
    exactly_2_a(2,1),
    set_abc_star(2),
    set_abc_plus(2),
    seq_abc_star(2),
    seq_abc_plus(2),
    a_star_b_star(),
    a_plus_b_plus()
]

FSAS_3SYM = [
    even_a(3, 0),
    even_a(3, 1),
    even_a(3, 2),
    exactly_2_a(3,0),
    exactly_2_a(3,1),
    exactly_2_a(3,2),
    set_abc_star(3),
    set_abc_plus(3),
    seq_abc_star(3),
    seq_abc_plus(3),
]

FSA_SETS = [FSAS_2SYM, FSAS_3SYM]


if __name__ == "__main__":
    q = language_of_fsa()
    print(q)

    import tkinter as tk
    import PIL.ImageTk
    root = tk.Tk()
    image = PIL.ImageTk.PhotoImage(q.promptfigure)
    label = tk.Label(root, image=image)
    label.pack()
    root.mainloop()
